name: Generate Font Previews Image

on:
  workflow_dispatch:  # Allows for manual triggering

permissions:
  contents: write  # Grant write access to repository contents

jobs:
  generate-previews:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ImageMagick
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick

      - name: Generate Font Preview Images
        run: |
          # Set the base fonts directory
          FONT_DIR="./public/fonts"
          
          # Loop through each font directory
          for dir in $(find $FONT_DIR -type d); do
            FONT_FILE=$(find $dir -type f -name "*.woff2" | head -n 1)  # Find the .woff2 font file
            if [ -z "$FONT_FILE" ]; then
              echo "No .woff2 font file found in $dir"
              continue
            fi

            # Set output preview file path
            OUTPUT_FILE="$dir/font-preview.png"

            # Generate the font preview image using ImageMagick
            convert -size 1280x720 xc:white -gravity center \
              -font "$FONT_FILE" -pointsize 72 -fill black \
              -annotate +0-200 "$FONT_NAME Font" \
              -font "$FONT_FILE" -pointsize 48 \
              -annotate +0+0 "\u0986\u09AE\u09BE\u09B0 \u09B8\u09CB\u09A8\u09BE\u09B0 \u09AC\u09BE\u0992\u09B2\u09BE, \u0986\u09AE\u09BF \u09A4\u09CB\u09AE\u09BE\u098F \u09AC\u09B2\u09B2\u09BE\u099B\u09BF আমি তোমায় ভালোবাসি" \
              -font "$FONT_FILE" -pointsize 24 -fill gray \
              -annotate +0+200 "banglawebfonts.pages.dev" \
              "$OUTPUT_FILE"
            
            echo "Preview generated for $dir"
          done

      - name: Commit and push images
        run: |
          git config --global user.name "fuadhasanshihab"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Generate font preview images"
          git push https://github.com/${{ github.repository }}.git HEAD:${{ github.ref }} 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
