name: Generate Font Package JSONs

on:
  workflow_dispatch:

jobs:
  generate-packages:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Validate fonts.json
        run: |
          if [ ! -f "./src/collections/fonts.json" ]; then
            echo "Error: fonts.json file not found!"
            exit 1
          fi
          if ! jq empty "./src/collections/fonts.json"; then
            echo "Error: fonts.json is not a valid JSON file!"
            exit 1
          fi
        shell: bash

      - name: Generate package.json for each font
        run: |
          node <<EOF
          const fs = require("fs");
          const path = require("path");

          const fontsDir = "./public/fonts";
          const fontsDataPath = "./src/collections/fonts.json";

          const fontsData = JSON.parse(fs.readFileSync(fontsDataPath, "utf-8"));

          fontsData.forEach((fontData) => {
              const fontPath = path.join(fontsDir, fontData.FontPath);
              if (!fs.existsSync(fontPath) || !fs.statSync(fontPath).isDirectory()) return;

              const packageJson = {
                name: "@banglawebfonts/" + fontData.FontPath,
                version: "1.0.0",
                description: fontData.FontName + " web font for Bangla Web Fonts",
                main: "index.css",
                publishConfig: {"access": "public"},
                files: ["*.css", "*.woff2", "*.woff", "*.jpg"],
                keywords: [
                  "bangla",
                  "font",
                  "webfont",
                  fontData.FontName.toLowerCase()
                ],
                author: fontData.FontDesigner,
                license: fontData.FontLicense,
                homepage: "https://banglawebfonts.pages.dev/" + fontData.FontPath + "/",
                repository: {
                  "type": "git",
                  "url": "git+https://github.com/fuadhasanshihab/bangla-web-fonts.git",
                  "directory": "public/fonts/" + fontData.FontPath
                },
              };

              fs.writeFileSync(path.join(fontPath, "package.json"), JSON.stringify(packageJson, null, 2));
              console.log("Created package.json for:", fontData.FontPath);
          });
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "fuadhasanshihab"
          git config --global user.email "85599261+fuadhasanshihab@users.noreply.github.com"
          git add .
          git commit -m "Update package.json" || exit 0
          git push origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
