name: Generate ReadMe Files for Fonts

on:
  push:
    branches:
      - update-020425  # Change this to the desired branch name
  workflow_dispatch:

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Generate Readme files
      run: |
        # Debug: Print the current working directory and list files
        echo "Current directory:"
        pwd
        echo "Listing files in the repository:"
        ls -al

        # Read fonts.json and loop through each font
        FONT_JSON_PATH="./src/collections/fonts.json"

        # Check if fonts.json exists
        if [ ! -f "$FONT_JSON_PATH" ]; then
          echo "fonts.json not found at $FONT_JSON_PATH"
          exit 1
        fi

        echo "Found fonts.json, proceeding with readme creation..."

        # Loop through each font entry in the JSON (Using grep and sed for simplicity)
        grep -oP '\{.*?\}' $FONT_JSON_PATH | while read font; do
          # Extract values using grep (without jq)
          FONT_NAME=$(echo "$font" | grep -oP '"FontName": *"\K([^"]+)' )
          FONT_PATH=$(echo "$font" | grep -oP '"FontPath": *"\K([^"]+)' )
          FONT_FAMILY=$(echo "$font" | grep -oP '"FontFamily": *"\K([^"]+)' )
          FONT_WEIGHTS=$(echo "$font" | grep -oP '"FontWeights": *\[(.*?)\]' | sed 's/\[//;s/\]//')
          FONT_TESTER_WEIGHTS=$(echo "$font" | grep -oP '"FontTesterWeights": *\[(.*?)\]' | sed 's/\[//;s/\]//')
          FONT_DESIGNER=$(echo "$font" | grep -oP '"FontDesigner": *"\K([^"]+)' )
          FONT_DESIGNER_URL=$(echo "$font" | grep -oP '"FontDesignerURL": *"\K([^"]+)' )
          FONT_LICENSE=$(echo "$font" | grep -oP '"FontLicense": *"\K([^"]+)' )

          # Debug: Print the extracted values
          echo "Creating readme for $FONT_NAME at $FONT_PATH"

          # Create directory if it doesn't exist
          FONT_DIR="./public/fonts/$FONT_PATH"
          mkdir -p $FONT_DIR

          # Debug: Confirm directory creation
          echo "Directory created at: $FONT_DIR"
          ls -al $FONT_DIR

          # Create the readme.md file
          echo -e "# $FONT_NAME\n\n## Font Family\n\`\`\`\n$FONT_FAMILY\n\`\`\`\n\n## Font Weights\n$FONT_WEIGHTS\n\n## Font Tester Weights\n$FONT_TESTER_WEIGHTS\n\n## Font Designer\n[$FONT_DESIGNER]($FONT_DESIGNER_URL)\n\n## Font License\n$FONT_LICENSE" > "$FONT_DIR/readme.md"

          # Debug: Confirm file creation
          if [ -f "$FONT_DIR/readme.md" ]; then
            echo "readme.md created for $FONT_NAME"
          else
            echo "Failed to create readme.md for $FONT_NAME"
          fi
        done

    - name: Commit changes
      run: |
        # Check if there are any changes to commit
        git add .
        git status

        # If there are any changes (new readme files), commit them
        if [[ $(git status --porcelain) ]]; then
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Generated readme.md files for fonts"
          git push origin update-020425
        else
          echo "No changes to commit"
        fi
