name: Generate Font READMEs

on:
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  generate-readmes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Update README files
        run: |
          node <<EOF
          const fs = require("fs");
          const path = require("path");

          const fontsDir = "./public/fonts";
          const readmeContent = `# FontName
This directory contains the FontName webfont files.

## CSS Stylesheet
\`\`\`css
https://banglawebfonts.pages.dev/css/FontName.css
\`\`\`

## Font Details
Visit https://banglawebfonts.pages.dev/FontName/#about for font designer, styles, license information.
`;

          fs.readdirSync(fontsDir).forEach((fontName) => {
              const fontPath = path.join(fontsDir, fontName);
              if (fs.statSync(fontPath).isDirectory()) {
                  const readmePath = path.join(fontPath, "README.md");

                  // Create or update the README.md file
                  const updatedReadmeContent = readmeContent.replace(/FontName/g, fontName);
                  fs.writeFileSync(readmePath, updatedReadmeContent);
                  console.log(\`Updated: \${readmePath}\`);
              }
          });
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update README.md files with new content" || exit 0
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
