name: Generate Font READMEs

on:
  workflow_dispatch:

jobs:
  generate-readmes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Generate or Update README files
        run: |
          node <<EOF
          const fs = require("fs");
          const path = require("path");

          const fontsDir = "./public/fonts";
          const readmeContent = "# FontName\n\nThis directory contains FontName font files.\n\n## CSS Stylesheet:\n\`\`\`css\nhttps://banglawebfonts.pages.dev/css/FontName.css\n\`\`\`\n\n## Font Details\nVisit https://banglawebfonts.pages.dev/FontName/#about for font designer, styles, license information.";

          fs.readdirSync(fontsDir).forEach((fontName) => {
              const fontPath = path.join(fontsDir, fontName);
              if (fs.statSync(fontPath).isDirectory()) {
                  const readmePath = path.join(fontPath, "README.md");
                  const content = readmeContent.replace("FontName", fontName);

                  // If README.md exists, update it, otherwise create it
                  if (fs.existsSync(readmePath)) {
                      fs.writeFileSync(readmePath, content);
                      console.log(`Updated: ${readmePath}`);
                  } else {
                      fs.writeFileSync(readmePath, content);
                      console.log(`Created: ${readmePath}`);
                  }
              }
          });
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-generate or update README.md for fonts" || exit 0
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
