name: Generate Font READMEs

on:
  workflow_dispatch:

jobs:
  generate-readmes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Generate or Update README files
        run: |
          node <<EOF
          const fs = require("fs");
          const path = require("path");

          const fontsDir = "./public/fonts";
          const fontsDataPath = "./src/collections/fonts.json";
          
          if (!fs.existsSync(fontsDataPath)) {
              console.error("fonts.json file not found!");
              process.exit(1);
          }

          const fontsData = JSON.parse(fs.readFileSync(fontsDataPath, "utf-8"));

          fs.readdirSync(fontsDir).forEach((fontFolder) => {
              const fontPath = path.join(fontsDir, fontFolder);
              if (fs.statSync(fontPath).isDirectory()) {
                  const fontData = fontsData.find(f => f.FontPath === fontFolder);
                  if (!fontData) {
                      console.warn(\`No metadata found for font folder: \${fontFolder}\`);
                      return;
                  }

                  const readmeContent = \`# \${fontData.FontName}

This directory contains the "\${fontData.FontName}" font files.

## CSS Stylesheet:
\`\`\`css
@import url('https://banglawebfonts.pages.dev/css/\${fontData.FontPath}.css');
\`\`\`

## Font Details:
- **Total Styles:** \${fontData.TotalStyles}
- **Font Family:** \${fontData.FontFamily}
- **Available Weights:** \${fontData.FontWeights.join(", ")}
- **Font Designer:** [\${fontData.FontDesigner}](\${fontData.FontDesignerURL})
- **License:** \${fontData.FontLicense}

For more details, visit: [\${fontData.FontName} on Bangla Web Fonts](https://banglawebfonts.pages.dev/\${fontData.FontPath}/#about).
\`;

                  const readmePath = path.join(fontPath, "README.md");
                  fs.writeFileSync(readmePath, readmeContent);
                  console.log(\`Processed: \${readmePath}\`);
              }
          });
          EOF

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Auto-generate or update README.md for fonts" || exit 0
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
