name: Generate Font Previews

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-previews:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Generate font previews
        run: |
          node -e "
          const puppeteer = require('puppeteer');
          const fs = require('fs');
          const path = require('path');

          function toFontFamily(name) {
            return name.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
          }

          async function generateFontPreview(fontDir) {
            const fontFolder = path.basename(fontDir);
            const fontFamily = toFontFamily(fontFolder);

            const browser = await puppeteer.launch({
              args: ['--no-sandbox', '--disable-setuid-sandbox']
            });
            const page = await browser.newPage();

            const html = \`
              <html>
                <head>
                  <link rel="preload" href="https://banglawebfonts.pages.dev/fonts/\${fontFolder}/\${fontFolder}-regular.woff2" as="font" type="font/woff2" crossorigin="anonymous">
                  <link rel="preload" href="https://banglawebfonts.pages.dev/fonts/anek-bangla/anek-bangla-regular.woff2" as="font" type="font/woff2" crossorigin="anonymous">
                  <link rel="preload" href="https://i.ibb.co.com/HfGtY5WX/20250428-203541.jpg" as="image">
                  <link href="https://banglawebfonts.pages.dev/css/webfonts.min.css" rel="stylesheet">
                  <style>
                    body {
                      margin: 0;
                      padding: 0;
                      width: 1200px;
                      height: 630px;
                      display: flex;
                      justify-content: center;
                      align-items: center;
                      background-color: #ffffff;
                      font-size: 56px;
                      font-family: 'Anek Bangla', sans-serif;
                      position: relative;
                      overflow: hidden;
                      line-height: 1.3;
                    }
                    body img {
                      position: absolute;
                      width: 1200px;
                      height: 630px;
                      z-index: -1;
                    }
                    .container {
                      text-align: center;
                      max-width: 90%;
                    }
                    .font-link {
                      position: absolute;
                      bottom: 40px;
                      left: 50%;
                      transform: translateX(-50%);
                      font-size: 24px;
                      color: #555;
                    }
                    .bangla-text {
                      font-family: '\${fontFamily}', sans-serif;
                      font-size: 56px;
                      margin-top: 20px;
                    }
                  </style>
                </head>
                <body>
                  <img src="https://i.ibb.co.com/HfGtY5WX/20250428-203541.jpg" alt="background">
                  <div class="container">
                    <div>\${fontFamily}</div>
                    <div class="bangla-text">আমার সোনার বাংলা<br/>আমি তোমায় ভালোবাসি</div>
                    <div class="font-link">banglawebfonts.pages.dev/font/\${fontFolder}</div>
                  </div>
                </body>
              </html>
            \`;

            await page.setViewport({ width: 1200, height: 630 });
            await page.setContent(html, { waitUntil: 'networkidle0' });
            await page.evaluateHandle('document.fonts.ready');

            const outputPath = path.join(fontDir, 'font-preview.png');
            await page.screenshot({ path: outputPath });
            await browser.close();
          }

          async function main() {
            const baseDir = path.join('public', 'fonts');
            const folders = fs.readdirSync(baseDir).filter(file => fs.statSync(path.join(baseDir, file)).isDirectory());

            for (const folder of folders) {
              const fontDir = path.join(baseDir, folder);
              console.log('Generating preview for', folder);
              await generateFontPreview(fontDir);
            }
          }

          main().catch(err => { console.error(err); process.exit(1); });
          "

      - name: Commit and Push generated previews
        run: |
          git config --global user.name 'fuadhasanshihab'
          git config --global user.email '85599261+fuadhasanshihab@users.noreply.github.com'
          git add public/fonts/**/font-preview.png
          git commit -m "Update font preview images"
          git push
